baseURL = "https://itztree.github.io/TechBlog/"
theme = "congo"
defaultContentLanguage = "ko"

enableRobotsTXT = true
summaryLength = 40

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
